package com.paulsen.wedding.model.newRsvp;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.paulsen.wedding.model.newRsvp.converters.EventConverter;
import com.paulsen.wedding.model.newRsvp.converters.GuestInfoConverter;
import com.paulsen.wedding.model.newRsvp.converters.RsvpGuestDetailsMapConverter;

import java.util.Map;

@DynamoDBTable(tableName="wedding_rsvp_table") public class Rsvp {

    @DynamoDBHashKey(attributeName="rsvp_id")
    @DynamoDBAutoGeneratedKey
    private String rsvpId;

    @DynamoDBAttribute(attributeName="is_submitted")
    private boolean isSubmitted;

    @DynamoDBAttribute(attributeName="primary_contact") @DynamoDBTypeConverted(converter=GuestInfoConverter.class)
    private GuestInfo primaryContact;

    @DynamoDBAttribute(attributeName="guest_list") @DynamoDBTypeConverted(converter=RsvpGuestDetailsMapConverter.class)
    private Map<String, RsvpGuestDetails> guestList;

    @DynamoDBAttribute(attributeName="roce") @DynamoDBTypeConverted(converter=EventConverter.class)
    private Event roce;

    @DynamoDBAttribute(attributeName="rehearsal") @DynamoDBTypeConverted(converter=EventConverter.class)
    private Event rehearsal;

    @DynamoDBAttribute(attributeName="ceremony") @DynamoDBTypeConverted(converter=EventConverter.class)
    private Event ceremony;

    @DynamoDBAttribute(attributeName="reception") @DynamoDBTypeConverted(converter=EventConverter.class)
    private Event reception;

    public String getRsvpId() {
        return rsvpId;
    }

    public void setRsvpId(String rsvpId) {
        this.rsvpId = rsvpId;
    }

    public boolean isSubmitted() {
        return isSubmitted;
    }

    public void setSubmitted(boolean submitted) {
        isSubmitted = submitted;
    }

    public GuestInfo getPrimaryContact() {
        return primaryContact;
    }

    public void setPrimaryContact(GuestInfo primaryContact) {
        this.primaryContact = primaryContact;
    }

    public Map<String, RsvpGuestDetails> getGuestList() {
        return guestList;
    }

    public void setGuestList(Map<String, RsvpGuestDetails> guestList) {
        this.guestList = guestList;
    }

    public Event getRoce() {
        return roce;
    }

    public void setRoce(Event roce) {
        this.roce = roce;
    }

    public Event getRehearsal() {
        return rehearsal;
    }

    public void setRehearsal(Event rehearsal) {
        this.rehearsal = rehearsal;
    }

    public Event getCeremony() {
        return ceremony;
    }

    public void setCeremony(Event ceremony) {
        this.ceremony = ceremony;
    }

    public Event getReception() {
        return reception;
    }

    public void setReception(Event reception) {
        this.reception = reception;
    }
}
